### ISSUE TITLE
Add flash to ctx.state?

### ISSUE THREAD

**Issue by Kilian** [niftylettuce/koa-better-flash#2]
Usually you want to show the flash message in a template. With ctx.state being the primary way to share messages with templates, would it be a good idea to `ctx.state.flash = ctx.flash()`? 

I currently do this with a middleware:
```
exports.addFlashToState = () => {
  return async (ctx, next) => {
    ctx.state.flash = ctx.flash();
    await next();
  };
};
```
But that only works when you have multiple middlewares to pass through, and not in the case of e.g.:
```
router.post("profile", authenticated(), async ctx => {
  ctx.flash("success", "Profile successfully updated");
  await ctx.render("profile", {});
});
```

**Comment by niftylettuce** [comment]
see <https://github.com/ladjs/state-helper/blob/master/index.js#L16-L24>
